
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '&I\\]g\t`\xc4\xd9`\x9f\x1c{\xfcf\x12'
    
_lr_action_items = {'STRING':([3,],[7,]),'SHOW':([0,],[1,]),'NEWLINE':([4,5,6,7,],[8,-4,8,-3,]),'HASHTAG':([1,],[5,]),'PRINT':([0,],[3,]),'$end':([2,8,9,10,],[0,-5,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'end':([4,6,],[9,10,]),'string':([3,],[6,]),'statement':([0,],[2,]),'hashtag':([1,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINT string end','statement',3,'p_statement_print','instat.py',65),
  ('statement -> SHOW hashtag end','statement',3,'p_statement_show','instat.py',71),
  ('string -> STRING','string',1,'p_string','instat.py',77),
  ('hashtag -> HASHTAG','hashtag',1,'p_hashtag','instat.py',82),
  ('end -> NEWLINE','end',1,'p_end','instat.py',87),
]
